// <auto-generated />
using System;
using EX.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EX.Data.Migrations
{
    [DbContext(typeof(EXContext))]
    [Migration("20240515145916_BibliotheqNasri")]
    partial class BibliotheqNasri
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EX.Core.Domain.Abonne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCrearion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Abonne");
                });

            modelBuilder.Entity("EX.Core.Domain.Categorie", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("EX.Core.Domain.Livre", b =>
                {
                    b.Property<int>("LivreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LivreId"));

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbrExemplaires")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("categfk")
                        .HasColumnType("int");

                    b.HasKey("LivreId");

                    b.HasIndex("categfk");

                    b.ToTable("Livre");
                });

            modelBuilder.Entity("EX.Core.Domain.PretLivre", b =>
                {
                    b.Property<DateTime>("DateDeubt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AbonneFk")
                        .HasColumnType("int");

                    b.Property<int>("LivreFk")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.HasKey("DateDeubt", "AbonneFk", "LivreFk");

                    b.HasIndex("AbonneFk");

                    b.HasIndex("LivreFk");

                    b.ToTable("PretLivre");
                });

            modelBuilder.Entity("EX.Core.Domain.Livre", b =>
                {
                    b.HasOne("EX.Core.Domain.Categorie", "MyCategorie")
                        .WithMany("Livres")
                        .HasForeignKey("categfk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyCategorie");
                });

            modelBuilder.Entity("EX.Core.Domain.PretLivre", b =>
                {
                    b.HasOne("EX.Core.Domain.Abonne", "MyAbonne")
                        .WithMany("PretLivres")
                        .HasForeignKey("AbonneFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EX.Core.Domain.Livre", "MyLivre")
                        .WithMany("PretLivres")
                        .HasForeignKey("LivreFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyAbonne");

                    b.Navigation("MyLivre");
                });

            modelBuilder.Entity("EX.Core.Domain.Abonne", b =>
                {
                    b.Navigation("PretLivres");
                });

            modelBuilder.Entity("EX.Core.Domain.Categorie", b =>
                {
                    b.Navigation("Livres");
                });

            modelBuilder.Entity("EX.Core.Domain.Livre", b =>
                {
                    b.Navigation("PretLivres");
                });
#pragma warning restore 612, 618
        }
    }
}
